Resources:
  AWSEBAutoScalingLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      # give the template a name based on your EB env
      LaunchTemplateName:
        Fn::Sub: "${AWSEBEnvironmentName}-LaunchTemplate"

      LaunchTemplateData:
        # attach the EC2 instance profile so EB can launch instances
        IamInstanceProfile:
          Name: aws-elasticbeanstalk-ec2-role

        # enlarge & encrypt your root volume
        BlockDeviceMappings:
          - DeviceName: "/dev/xvda"
            Ebs:
              VolumeSize: 100
              VolumeType: gp3
              Encrypted: true
